version: "3.9"

services:
  backend:
    container_name: nest_backend_dev
    build:
      context: ./doctor-prescription-core
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./doctor-prescription-core:/app
      - /app/node_modules
    env_file:
      - ./doctor-prescription-core/.env
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql_dev
    ports:
      - "3307:3306"   # host:container
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: prescription_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
